server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bookSystem?characterEncoding=utf-8&useSSL=false
    username: root
    password: li197910
    hikari:
      # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省值：30 分钟，建议设置比数据库超时时长少 30 秒以上
      maxLifetime: 1765000
      # 连接池中允许的最大连接数。缺省值：10，推荐的公式：((core_count * 2) + effective_spindle_count)
      maximumPoolSize: 15
  http:
    encoding:
      charset: utf-8
      enabled: true
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  redis:
    host: 127.0.0.1
    port: 6379
